const quotationData = [
  {
    title: "efficiency",
    quotationText: "Lorem Ipsum",
    profit_loss: "1.1921",
    profit_loss_Details: "+0.0015 (+0.13%)",
    cost: "0.00 USD",
    color: "white",
    backgroundColor: "#8EBAE3",
    backgroundImage: "./quotationIcon/Path-1.png",
    arrow: "./quotationIcon/Arrow-Up.png",
    currColor: "#D9EAFF",
  },
  {
    title: "time to market",
    quotationText: "Lorem Ipsum",
    profit_loss: "327,176",
    profit_loss_Details: "-97,914.00 (-23.03%)",
    cost: "131,040,723,108 JPY",
    color: "white",
    backgroundColor: "#14827B",
    backgroundImage: "./quotationIcon/Path-2.png",
    arrow: "./quotationIcon/Arrow.png",
    currColor: "#FFEEB2",
  },
  {
    title: "tech debt",
    quotationText: "Lorem Ipsum",
    profit_loss: "1.1763",
    profit_loss_Details: "+0.0015 (+0.13%)",
    cost: "0.00 USD",
    color: "black",
    backgroundColor: "#FFFFFF",
    backgroundImage: "./quotationIcon/Path-3.png",
    arrow: "./quotationIcon/Arrow-dark.png",
    currColor: "#939699",
  },
  {
    title: "predictablity",
    quotationText: "Lorem Ipsum",
    profit_loss: "0.00313010",
    profit_loss_Details: "-0.00050430 (-13.88%",
    cost: "1,566 BTC",
    color: "white",
    backgroundColor: "#FF4F52",
    backgroundImage: "./quotationIcon/Path-4.png",
    arrow: "./quotationIcon/Arrow.png",
    currColor: "#FFC4C9",
  },
];

export default quotationData;
